variables:
  TF_DIR: "infrastructure"

stages:
  - terraform-plan
  - terraform-apply
  - terraform-destroy


terraform-plan:
  image: 
    name: hashicorp/terraform:1.8
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: terraform-plan
  script:
    - terraform -chdir=$TF_DIR init
    - terraform -chdir=$TF_DIR plan

terraform-apply:
  stage: terraform-apply
  script:
    - echo "Terraform apply"

terraform-destroy:
  stage: terraform-destroy
  script:
    - echo "Terraform destroy"

