variables:
  TF_DIR: "infrastructure"

stages:
  - terraform-plan
  - terraform-apply
  - terraform-destroy


terraform-plan:
  image: hashicorp/terraform:1.8
  stage: terraform-plan
  script:
    - terraform -chdir=$TF_DIR init

terraform-apply:
  stage: terraform-apply
  script:
    - echo "Terraform apply"

terraform-destroy:
  stage: terraform-destroy
  script:
    - echo "Terraform destroy"

