services:
 postgres-server:
  image: "${POSTGRESQL_IMAGE}:${POSTGRESQL_IMAGE_TAG}"
#  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  restart: "${RESTART_POLICY}"
  volumes:
   - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ${ENV_VARS_DIRECTORY}/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ${ENV_VARS_DIRECTORY}/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  env_file:
   - ${ENV_VARS_DIRECTORY}/.pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_database:
    aliases:
     - postgres-server

 db-data-pgsql:
  image: busybox
  volumes:
   - ${DATA_DIRECTORY}/var/lib/postgresql/data:/var/lib/postgresql/data:rw